/**
 * GET /api/cron/daily-brief
 *
 * Called by Vercel Cron at 3:00 UTC daily (7am AKST / 11am AKST daylight).
 * Authenticated via CRON_SECRET header to prevent unauthorized triggers.
 *
 * Also callable manually via the dashboard for on-demand generation.
 */
import { Resend } from "resend";

export async function GET(request: Request) {
  // Verify cron secret — Vercel sends this automatically when configured
  const authHeader = request.headers.get("authorization");
  const cronSecret = process.env.CRON_SECRET;

  if (!cronSecret || authHeader !== `Bearer ${cronSecret}`) {
    return Response.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    // Re-use the existing generate endpoint logic by calling it internally
    const origin =
      process.env.NEXT_PUBLIC_APP_URL ||
      (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : "http://localhost:3000");

    const res = await fetch(`${origin}/api/briefs/generate`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        // Forward cron secret so generate route can also be protected if needed
        ...(cronSecret ? { authorization: `Bearer ${cronSecret}` } : {}),
      },
      body: JSON.stringify({ context: "This is an automated morning brief. Be comprehensive." }),
    });

    if (!res.ok) {
      const err = await res.json().catch(() => ({ error: res.statusText }));
      console.error("[cron/daily-brief] generate failed:", err);
      return Response.json(
        { error: "Brief generation failed", detail: err },
        { status: res.status }
      );
    }

    const result = await res.json();
    console.log("[cron/daily-brief] Brief generated successfully:", result.brief?.id);

    // Email the brief to Scott
    if (process.env.RESEND_API_KEY) {
      try {
        const resend = new Resend(process.env.RESEND_API_KEY);
        const brief = result.brief;
        const sections = Array.isArray(brief?.sections)
          ? (brief.sections as Array<{ title: string; items: Array<{ headline: string; whyItMatters: string; score: string }> }>)
              .map(
                (s) =>
                  `<h3>${s.title}</h3>` +
                  s.items
                    .map(
                      (item) =>
                        `<p><strong>[${item.score}] ${item.headline}</strong><br/>${item.whyItMatters}</p>`
                    )
                    .join("")
              )
              .join("")
          : "";

        await resend.emails.send({
          from: "Chapterhouse <noreply@buttercup.cfd>",
          to: "scott@nextchapterhomeschool.com",
          subject: `Daily Brief — ${brief?.title ?? new Date().toLocaleDateString()}`,
          html: `<h2>${brief?.title ?? "Daily Brief"}</h2>
            <p>${brief?.summary ?? ""}</p>
            ${sections}
            <hr/>
            <p style="color:#888;font-size:12px;">Generated by Chapterhouse at ${new Date().toISOString()}</p>`,
        });
        console.log("[cron/daily-brief] Email sent to scott@nextchapterhomeschool.com");
      } catch (emailErr) {
        console.warn("[cron/daily-brief] Email send failed (non-fatal):", emailErr);
      }
    }

    // Stage 3: Create an Intel session with the brief content so chat gets deep analysis.
    // This is how the Intel system "replaces" the brief — same daily data, full Intel scoring.
    // Fire-and-forget — brief cron response is already committed before this runs.
    {
      const briefForIntel = result.brief;
      if (briefForIntel?.sections) {
        type BriefItem = { headline: string; whyItMatters: string; score: string; collision_note?: string };
        type BriefSection = { title: string; items: BriefItem[] };
        const briefAsText = [
          `DAILY BRIEF — ${briefForIntel.title ?? new Date().toLocaleDateString()}`,
          "",
          briefForIntel.summary ?? "",
          "",
          ...(briefForIntel.sections as BriefSection[]).map((s) =>
            `## ${s.title}\n` +
            s.items.map((item) =>
              `[${item.score}] ${item.headline}\n${item.whyItMatters}` +
              (item.collision_note ? `\nCross-track signal: ${item.collision_note}` : "")
            ).join("\n\n")
          ),
        ].join("\n");

        fetch(`${origin}/api/intel`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            urls: [],
            extra_content: briefAsText,
            source_type: "manual", // avoids conflicting with intel-fetch cron dedup
            session_label: `Brief Intel — ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}`,
          }),
        })
          .then((r) => r.json())
          .then((s: { session?: { id?: string } }) =>
            console.log("[cron/daily-brief] Intel session created:", s.session?.id ?? "unknown")
          )
          .catch((e: unknown) =>
            console.warn("[cron/daily-brief] Intel session creation failed (non-fatal):", e)
          );
      }
    }

    // Stage 4: after brief generates, run the summarization pass to keep
    // the knowledge base current. Fire-and-forget — don't block this response.
    fetch(`${origin}/api/summarize`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...(cronSecret ? { authorization: `Bearer ${cronSecret}` } : {}),
      },
    })
      .then((r) => r.json())
      .then((s) => console.log("[cron/daily-brief] Summarization pass:", s.message))
      .catch((e) => console.warn("[cron/daily-brief] Summarization pass failed (non-fatal):", e));

    return Response.json({
      ok: true,
      briefId: result.brief?.id ?? null,
      meta: result.meta ?? null,
      generatedAt: new Date().toISOString(),
    });
  } catch (error) {
    console.error("[cron/daily-brief] Unexpected error:", error);
    return Response.json({ error: String(error) }, { status: 500 });
  }
}
